services:
  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile


  promotionservice:
    image: ${DOCKER_REGISTRY-}promotionservice
    build:
      context: .
      dockerfile: PromotionService/Dockerfile


  reviewservice:
    image: ${DOCKER_REGISTRY-}reviewservice
    build:
      context: .
      dockerfile: ReviewService/Dockerfile


  shippingservice:
    image: ${DOCKER_REGISTRY-}shippingservice
    build:
      context: .
      dockerfile: ShippingService/Dockerfile

